#Author: Muhammad Usman Hasan
SELECT IF(GRADE<8,NULL,NAME), GRADE, MARKS
FROM
STUDENTS S LEFT JOIN GRADES G ON
MARKS BETWEEN MIN_MARK AND MAX_MARK
ORDER BY GRADE DESC,
(CASE  
WHEN GRADE BETWEEN 8 AND 10 THEN  NAME 
ELSE  MARKS 
END);
